name: lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: Install dependencies
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
